//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeVendorAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string EmployeeId { get; set; }
        public string Surname { get; set; }
        public string OtherName { get; set; }
        public string D_O_B { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string ResumptionDate { get; set; }
        public string Qualification { get; set; }
        public string Department { get; set; }
        public string Salary { get; set; }
    }
}
